### ISSUE TITLE
openssl 1.1.0 compatibility

### ISSUE THREAD

**Issue by dfateyev** [halon/libdkimpp#2]
I experience issues trying to rebuild libdkimpp against openssl-1.1.0e (which is landed to Fedora devel). Seems not compatible with this branch, please see [18270389 build log](https://kojipkgs.fedoraproject.org//work/tasks/389/18270389/build.log) for more details.

**Comment by eriklax** [comment]
Thanks for the report. I updated the library and released 1.0.10 to support openssl 1.1.0-e (from rawhide on Fedora 25) which has some major changes in it's API.

9d7a05a133415713ca1bc3cbd36233d5c8bf4820
b09ab078c602444a4c5ad45c37c5d205a5983cf5
eacf846c49f67dc8fe79222d34957ec804132f77
04de8749272192e3d94111b898ca7dbdd366ced0
54c7c400a46725a136c8298eb773c8a33cc9c882
