### ISSUE TITLE
Crash on Signatory::CreateSignature with libcrypto.so.1.1

### ISSUE THREAD

**Issue by MatthieuTexier** [halon/libdkimpp#3]
Since upgrade of my Debian system to stretch I crash on EVP_MD_CTX_reset call in CreateSignature function with "free(): invalid next size (fast)"

**Comment by eriklax** [comment]
Are you using the latest git head? This change may be related.

54c7c400a46725a136c8298eb773c8a33cc9c882

**Comment by MatthieuTexier** [comment]
Yes, I do use the latest with this commit applied

**Comment by eriklax** [comment]
Could you provide some example code which crashes? I've install latest debian 9.0.0, with openssl 1.1.0f but having a hard time reproduce the problem.

**Comment by MatthieuTexier** [comment]
I, sorry for the very long wait.
My app is linking with licurl too that links to the 1.0 version library.
There is no issue with libdkimpp
